apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build
spec:
  steps:
  - name: checkout-code
    image: alpine
    workingDir: /workspace/shared-workspace
    workspaces:
    - name: shared-workspace
  - name: set-up-jdk-8
    image: alpine
    workingDir: /workspace/shared-workspace
    script: echo 'Using actions/setup-java@v3 is not yet supported'
    workspaces:
    - name: shared-workspace
  - name: build-with-maven
    image: alpine
    workingDir: /workspace/shared-workspace
    script: mvn clean install
    workspaces:
    - name: shared-workspace
  workspaces:
  - name: shared-workspace
