apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy
spec:
  steps:
  - name: checkout-code
    image: alpine
    workingDir: /workspace/shared-workspace
    workspaces:
    - name: shared-workspace
  - name: set-up-kubectl
    image: alpine
    workingDir: /workspace/shared-workspace
    script: echo 'Using azure/setup-kubectl@v1 is not yet supported'
    workspaces:
    - name: shared-workspace
  - name: deploy-to-kubernetes
    image: alpine
    workingDir: /workspace/shared-workspace
    script: kubectl apply -f deployment.yaml
    workspaces:
    - name: shared-workspace
  workspaces:
  - name: shared-workspace
