apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test
spec:
  steps:
  - name: checkout-code
    image: alpine
    workingDir: /workspace/shared-workspace
    workspaces:
    - name: shared-workspace
  - name: set-up-jdk-8
    image: alpine
    workingDir: /workspace/shared-workspace
    script: echo 'Using actions/setup-java@v3 is not yet supported'
    workspaces:
    - name: shared-workspace
  - name: run-tests
    image: alpine
    workingDir: /workspace/shared-workspace
    script: mvn test
    workspaces:
    - name: shared-workspace
  workspaces:
  - name: shared-workspace
