pipelines:
  default:
    - step:
        name: Build
        image: maven:3.6.3-jdk-8
        caches:
          - maven
        script:
          - mvn clean install
    - step:
        name: Test
        image: maven:3.6.3-jdk-8
        caches:
          - maven
        script:
          - mvn test
    - step:
        name: Deploy
        image: bitnami/kubectl:latest
        script:
          - kubectl apply -f deployment.yaml
        condition:
          changesets:
            includePaths:
              - "**/*.yaml"
