stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  image: maven:3.6.3-jdk-8
  script:
    - mvn clean install
  cache:
    paths:
      - .m2/repository

test:
  stage: test
  image: maven:3.6.3-jdk-8
  script:
    - mvn test
  cache:
    paths:
      - .m2/repository

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f deployment.yaml
  only:
    - main

